 # This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish: 
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v1
    - name: Setup Porter
      uses: deislabs/porter-gh-action@v0.1.1
      with:
        porter_version: v0.27.2
    - name: Install Docker mixin
      run: porter mixins install docker
    - name: Porter install
      run: porter install -c ./docker-example.json --allow-docker-host-access
    - name: Porter upgrade
      run: porter upgrade -c ./docker-example.json --allow-docker-host-access
    - name: Porter uninstall
      run: porter uninstall -c ./docker-example.json --allow-docker-host-access
    - uses: azure/docker-login@v1
      name: Docker Login
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Porter Publish
      run: porter publish
