 # This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish: 
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v1
    - name: Setup Porter
      uses: deislabs/porter-gh-action@master
    - uses: azure/docker-login@v1
      name: Docker Login
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Porter Publish
      run: porter publish
